# Generated by Django 5.2.6 on 2025-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_company_is_verified_company_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Accounts Receivable', 'Accounts Receivable (A/R)'), ('Other Current Assets', 'Other Current Assets'), ('Bank', 'Bank'), ('Fixed Assets', 'Fixed Assets'), ('Other Assets', 'Other Assets'), ('Accounts Payable', 'Accounts Payable (A/P)'), ('Credit Card', 'Credit Card'), ('Other Current Liabilities', 'Other Current Liabilities'), ('Long Term Liabilities', 'Long Term Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Other Income', 'Other Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Expenses', 'Expenses'), ('Other Expense', 'Other Expense')], max_length=50),
        ),
    ]
