# Generated by Django 5.2.6 on 2025-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
    ]
