# Generated by Django 5.2.6 on 2025-12-11 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_warehouse_unique_together_warehouse_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.purchaseorder'),
        ),
    ]
